<div class="container">
    <div class="row justify-content-center">
        <fieldset class="border border-2 rounded-3 p-3 col-md-12 mt-5">
            <legend class="float-none w-auto px-3 heading-section h2">Add Student</legend>
            <form action="" method="post">
                <div class="row">
                    <div class="form-group col-md-6 col-sm-12">
                        <label for="name">Student's Name</label>
                        <input type="text" class="form-control" name="name" id="name" placeholder="Enter Student's Name" required>
                    </div>
                    <div class="form-group col-md-6 col-sm-12">
                        <label for="rollno">Roll No.</label>
                        <input type="text" name="rollno" id="rollno" class="form-control" placeholder="Enter Roll Number" required>
                    </div>
                    <div class="form-group col-md-6 col-sm-12">
                        <label for="class">Class</label>

                        <select name="class" id="class" class="form-control form-select">
                            <option value="" selected>Select Class</option>
                            <?php
                            if (mysqli_num_rows($result) > 0) {
                                foreach ($result as $row) {
                            ?>
                                    <option value="<?= $row['id']; ?>"><?= $row['cname']; ?></option>
                            <?php
                                }
                            }
                            ?>
                        </select>
                    </div>
                    <div class="form-group col-md-6 col-sm-12">
                        <label for="city">City</label>
                        <input type="text" name="city" id="city" class="form-control" placeholder="Enter City Name">
                    </div>
                    <div class="form-group mt-2">
                        <!-- <input type="submit" value="Add Student" name="add" class="form-control"> -->
                        <button type="submit" class="btn btn-primary" name="add">Add Student</button>
                    </div>
                </div>
            </form>
        </fieldset>
    </div>
</div>