<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CRUD</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
    <nav  class="navbar mb-2 my-lg-0 navbar-expand-lg navbar-dark bg-secondary sticky-top">
        <div class="container-fluid">
          <a class="navbar-brand" href="./home.php">CRUD</a>
          <div class="navbar-brand justify-content-center">
            <span class="p">Welcome</span>
          </div>
          
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <ul class="navbar-nav  mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="./home.php">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="./add.php">Add</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="./home.php">List</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="./update.php">Update</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="./delete.php">Delete</a>
              </li>
              <li class="nav-item pull-right">
                <a class="nav-link" href="./logout.php">Logout</a>
              </li>
            </ul>
          </div>
          
          
        </div>
      </nav>
