<div class="container">
    <table class="table table-responsive">
        <thead>
            <tr class="table-danger">
                <th scope="col">ID</th>
                <th>Name</th>
                <th>Roll No.</th>
                <th>Class</th>
                <th>City</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <?php
                if(mysqli_num_rows($result)>0){
                    foreach($result as $row){
            ?>
            <tr class="table-warning">
                <th scope="row"><?= $row['id'];?></th>
                <th><?= $row['sname'];?></th>
                <th><?= $row['rolls'];?></th>
                <th><?= $row['cname'];?></th>
                <th><?= $row['city'];?></th>
                <th>
                    <button class="btn btn-primary"><a href="edit.php?id=<?= $row['id'];?>" class="text-white text-decoration-none">Edit</a></button>
                    <button class="btn btn-danger"><a href="delete.php?id=<?= $row['id'];?>" class="text-white text-decoration-none">Delete</a></button>
                </th>
            </tr>
            <?php
                }
            }
            ?>
        </tbody>
    </table>
</div>