<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>LogIn</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="./css/style.css">
</head>

<body>
    <section class="container">
        <div class="row justify-content-center">
            <fieldset class="border border-2 rounded-3 p-3 col-md-5 mt-5">
                <legend class="float-none w-auto px-3 heading-section h2">LogIn</legend>
                <div class="login-wrap p-4 p-md-5">
                    <!-- <div class="icon d-flex align-items-center justify-content-center">
                        <span class="fa fa-user-o"></span>
                    </div> -->
                    <h3 class="text-center mb-4"></h3>
                    <form action="" class="login-form" method="post">
                        <div class="form-group d-flex mb-2">
                            <input type="text" class="form-control rounded-left" name="username" placeholder="Email ID" required>
                        </div>
                        <div class="form-group d-flex mb-2">
                            <input type="password" class="form-control rounded-left" name="password" placeholder="Password" required>
                        </div>
                        <div class="form-group d-md-flex mb-2">
                            <div class="w-50">
                                <label class="checkbox-wrap checkbox-primary">Remember Me
                                    <input type="checkbox" name="rememberme" id="rememberme" checked>
                                    <span class="checkmark"></span>
                                </label>
                            </div>
                            <div class="w-50 text-md-right">
                                <a href="#" class="text-decoration-none">Forgot Password</a>
                            </div>
                        </div>
                        <div class="form-group d-flex mb-2">
                            <button type="submit" name="login" class="btn btn-primary rounded submit p-2 px-4">Login Now</button>
                        </div>
                    </form>
                </div>
            </fieldset>
        </div>
    </section>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>